### ISSUE TITLE
ENH: Rework academic module

### ISSUE THREAD

**Issue by jorgechp** [jorgechp/etsiit_bot#27]
## Enhancement description

We need to change the defined structure in the Academic module in order to apply the following changes:

1. It's required to create a class, AcademicInformation, which is compounded by three data structures (final degree project, internship and teaching guides).
2. Teaching guides will be implemented as a Link of dictionaries (subject, url).

**Comment by lulivi** [comment]
Closed in https://github.com/jorgechp/etsiit_bot/wiki/Class-Information/5b29aae34ddb1d37125b183cd91a417bd218a2d1
